export enum FeedbackStatus {
  RECEIVED = 'RECEIVED',
  IN_REVIEW = 'IN_REVIEW',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  NO_ACTION_NEEDED = 'NO_ACTION_NEEDED',
  PENDING = 'PENDING',
}
