export enum QueryKeys {
  ME = "me",
  USERS = "users",
  BASES = "bases",
  WELLS = "wells",
  CLIENTS = "clients",
  AVERAGE = "average",
  OCCURRENCES = "occurrences",
  OCCURRENCES_ACTIONS = "occurrences-actions",
  OCCURRENCES_TAXES = "occurrences-taxes",
  TOTAL_OCCURRENCES_TAXES = "total-occurrences-taxes",
  MAN_HOURS = "man-hours",
  PERIODS = "periods",
  EFFICIENCY = "efficiency",
  EFFICIENCIES = "efficiencies",
  BILLING = "billing",
  BILLINGS = "billings",
  CONTRACT_RIGS = "contract-rigs",
  CONFIG_BILLINGS = "config-billings",
  SYSTEM_VERSION = "system-version",
  UNBILLED_PERIODS = "unbilled-periods",
  DELETION_REQUESTS = "deletion-requests",
  TEMPORARY_EFFICIENCY = "temporary-efficiency",
  TEMPORARY_EFFICIENCIES = "temporary-efficiencies",
  RIGS_AVERAGE = "rigs-average",
  WELLS_COUNT = "wells-count",
  USER_LOGS = "user-logs",
}
