-- CreateEnum
CREATE TYPE "LogType" AS ENUM ('LOGIN', 'LOGOUT', 'PASSWORD_CHANGE', 'CONFIGURATION_CHANGE', 'DATA_EXPORT', 'BDO_CREATE', 'BDO_EDIT', 'BDO_DELETE', 'EFFICIENCY_VIEW', 'EFFICIENCY_CREATE', 'EFFICIENCY_EDIT', 'OCCURRENCE_CREATE', 'OCCURRENCE_EDIT', 'OCCURRENCE_DELETE', 'REPORT_GENERATION', 'VIEW_CRITICAL_DATA', 'ALERT_ACKNOWLEDGMENT', 'OTHER');

-- AlterTable
ALTER TABLE "UserLog" ADD COLUMN     "log_type" "LogType" NOT NULL DEFAULT 'LOGIN';
