version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - cd fe && npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync --delete ./dist s3://${DEPLOY_BUCKET} --recursive
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
