version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - ls
      - cd fe && npm ci

  build:
    commands:
      - ls
      - cd fe && npm run build
